# .github/workflows/deploy.yml
name: Copy Client to External Repo

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  #  push:
  #    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.JUKE_BOX_WEB_REPO_PAT }}

        with:
          # GitHub Action output files
          source-directory: jukebox-web/
          destination-github-username: jaico22
          destination-repository-name: jukebox-web
          user-email: admin@harmoni.app

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
